### ISSUE TITLE
Hello! I have some questions in your tiny state machine.

### ISSUE THREAD

**Issue by insooneelife** [MhmmdAb/TinyStateMachine#1]
Hello! Recently I'm trying to make c# style state machine.
I also saw open source project "stateless", but it was too big for me to understand..
And then I saw your tiny state machine, that the design was very impressive for me!
I also saw the test examples, but I still have some questions about this design.

It seems that this state machine works with Fire() method to change state to state, and some actions could be triggered.
But I can't see any update method for state machine. 
Which means, if I'm in some state, how can I run proper object action in that state?

For example, If I want to make some AI character that has some states{ Attack, Move, HoldPosition },
how can I use this tiny state machine with it?

I think I can just make if-else statement like ..

```
enum EntityState
{
    Attack, Move, HoldPosition
}
enum EntityEvent
{
    EnemyFound, FarToAttack
}

void Update()
{
    if (_state == EntityState.Attack)
    {
        if (EnemyInRange())
        {
            Attack();
        }
        else
        {
            _stateMachine.Fire(EntityEvent.FarToAttack);
        }
    }
    else if (_state == EntityState.Move)
    {
        //..
    }
    else if (_state == EntityState.HoldPosition)
    {
        if (EnemyInView())
        {
            _stateMachine.Fire(EntityEvent.EnemyFound);
        }
    }

}
```

Is this right approach for your state machine? Or am I missing something?

**Comment by insooneelife** [comment]
I considered a lot and made like this..

```
class Program
    {
        class Entity
        {
            enum EntityState
            {
                Attack, HoldPosition, WaitForNextAttack
            }

            enum EntityEvent
            {
                None, EnemyInRange, EnemyGone, AttackDelayFinished, AttackDelayNotFinished, DoneAttack
            }

            public Entity()
            {
                _state = EntityState.HoldPosition;
                _nextEvent = EntityEvent.None;

                _attackFrame = 0;
                _attackDelay = 10;

            _stateMachine = new TinyStateMachine<EntityState, EntityEvent>(_state);
                _stateMachine
                    .Tr(EntityState.HoldPosition, EntityEvent.EnemyInRange, EntityState.Attack)
                    .On(Attack)
                    .Tr(EntityState.HoldPosition, EntityEvent.None, EntityState.HoldPosition)
                    .On(HoldPosition)
                    .Tr(EntityState.Attack, EntityEvent.EnemyGone, EntityState.HoldPosition)
                    .On(HoldPosition)
                    .Tr(EntityState.Attack, EntityEvent.DoneAttack, EntityState.WaitForNextAttack)
                    .On(WaitForNextAttack)
                    .Tr(EntityState.WaitForNextAttack, EntityEvent.AttackDelayFinished, EntityState.Attack)
                    .On(Attack)
                    .Tr(EntityState.WaitForNextAttack, EntityEvent.AttackDelayNotFinished, EntityState.WaitForNextAttack)
                    .On(WaitForNextAttack);

            }

            public void Update()
            {
                _stateMachine.Fire(_nextEvent);
            }

            public void HoldPosition()
            {
                Console.WriteLine("HoldPosition()");
                if(InRange())
                {
                    _nextEvent = EntityEvent.EnemyInRange;
                }
            }

            public void Attack()
            {
                if (InRange())
                {
                    Console.WriteLine("Attack()");
                    _nextEvent = EntityEvent.DoneAttack;
                }
                else
                {
                    _nextEvent = EntityEvent.EnemyGone;
                }
            }

            public void WaitForNextAttack()
            {
                Console.WriteLine("WaitForNextAttack()");
                if ((_attackFrame++) % _attackDelay == 0)
                {
                    _nextEvent = EntityEvent.AttackDelayFinished;
                }
                else
                {
                    _nextEvent = EntityEvent.AttackDelayNotFinished;
                }
            }

            public bool InRange()
            {
                return true;
            }


            private EntityState _state;
            private EntityEvent _nextEvent;

            private int _attackFrame;
            private int _attackDelay;

            private TinyStateMachine<EntityState, EntityEvent> _stateMachine;
        }


        static void Main(string[] args)
        {
            Entity entity = new Entity();

            while(true)
            {
                entity.Update();
                System.Threading.Thread.Sleep(50);
            }
        }
    }
```

Is this design good as you expected for using your state machine?

**Comment by MhmmdAb** [comment]
Thanks for the kind words! I'm glad you liked it and I'm sorry for not providing any documentation. I have been working on a proper readme, but it still needs a few more hours of TLC before it's ready for publishing.

Back to your question.

It looks like the code snippet you have there is for a Unity behavior (or something very much like it), and that the update method is meant to be called once per frame. If that is case, then what you have there is a perfectly valid solution. In fact, it probably is the best solution for simple cases, which turns out to be most of the cases that I had to tackle in my game development projects.

But there's another way. When defining the states for the state machine, you don't have to use `enums`. Plain old objects would do just fine. So you can define a state interface like so:

``` csharp
  interface IEntityState
  {
    void Update();
  }
```

And then you can derive state classes from that:

``` csharp
  class AttackState : IEntityState
  {
    public void Update()
    {
      // Attack-specific code goes in here.
    }
  }

  class MoveState : IEntityState
  {
    public void Update()
    {
      // Move-specific code goes in here.
    }
  }
```

Then you can define the state machine like so:

``` csharp
  var attackState = new AttackState();
  var moveState = new MoveState();

  var stateMachine = new TinyStateMachine<IEntityState, EntityEvent>(moveState)
  stateMachine.Tr(moveState, EntityEvent.Attack, attackState)
              .Tr(attackState, EntityEvent.Move, moveState);
```

And then in your update method you would call `Update` on `IEntityState` directly:

``` csharp
  void Update()
  {
    stateMachine.State.Update();
  }
```

Hope this helps.

**Comment by MhmmdAb** [comment]
@insooneelife, I just saw your second post.

Just to make sure we are on the same page, it seems like you're using the FSM as the handler for your update loop, so that each update requires the state machine to trigger an event to process the inputs and decide what to do next. Does that sound right?

If that is the case, then yeah, it's fine. You're even taking care of making sure that the `HoldState` can transition to itself. So you're spot on.

**Comment by insooneelife** [comment]
Thank you for answering my question!
Awesome! It has incredible expandability that I have never experienced.
And your answer helped me a lot for realize that I don't have to make state by only enumerators.

**Comment by MhmmdAb** [comment]
Glad I was able to help. Watch this space for updated docs soon. -ish.
